_extends: .github
repository:
  name: eslint-config-template
  description: Shareable config for ESLint
  homepage: 'https://npm.im/@form8ion/eslint-config-template'
  private: false
  is_template: false
